#!/bin/bash
cd "$(dirname "$0")"

clean_cache=0
build_args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --clean-cache|--clean-caches|--clean)
            clean_cache=1
            shift
            ;;
        *)
            build_args+=("$1")
            shift
            ;;
    esac
done

if [[ "$clean_cache" = 1 ]]; then
    rm -rf .build .debug .deps .bundle
fi

source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help --ignore-shell-parser
if [[ ${#build_args[@]} -gt 0 ]]; then
    swift build "${build_args[@]}"
else
    swift build
fi
# swift build doesn't build test targets by default :(
# XCTest is unavailable with CommandLineTools-only setups, so skip this target in that environment.
if [[ "$(/usr/bin/xcode-select -p 2>/dev/null || true)" != *"CommandLineTools"* ]]; then
    if [[ ${#build_args[@]} -gt 0 ]]; then
        swift build --target AppBundleTests "${build_args[@]}"
    else
        swift build --target AppBundleTests
    fi
else
    echo "warning: Skipping AppBundleTests build (XCTest unavailable without full Xcode)" > /dev/stderr
fi

if [[ ${#build_args[@]} -gt 0 ]]; then
    bin_path="$(swift build --show-bin-path "${build_args[@]}")"
else
    bin_path="$(swift build --show-bin-path)"
fi
rm -rf .debug && mkdir .debug
cp "$bin_path/ddwm" .debug
cp "$bin_path/ddwmApp" .debug
