#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source ./script/setup.sh

usage() {
    cat <<EOF
Usage: ./script/dev.sh <command> [args...]

Commands:
  build-debug [--clean-cache|--clean-caches|--clean] [swift-build-args...]
  run-debug [app-args...]
  run-cli [cli-args...]
  run-swift-test
  run-tests
  format [--check-uncommitted-files]
  generate [generate-args...]
  generate-shell-parser
  build-shell-completion
  build-docs
  build-release [--build-version <v>] [--codesign-identity <id>]
  install-from-sources [--dont-rebuild]
EOF
}

cmd_generate_shell_parser() {
    ./script/install-dep.sh --antlr
    ./.deps/python-venv/bin/antlr4 -v "$antlr_version" -no-listener -Dlanguage=Swift \
        -o ./ShellParserGenerated/Sources/ShellParserGenerated \
        ./grammar/ShellLexer.g4 \
        ./grammar/ShellParser.g4

    mv ./ShellParserGenerated/Sources/ShellParserGenerated/grammar/*.swift ./ShellParserGenerated/Sources/ShellParserGenerated/
    rm -rf ./ShellParserGenerated/Sources/ShellParserGenerated/grammar
    sed -i '' '/_prevctx/d' ./ShellParserGenerated/Sources/ShellParserGenerated/ShellParser.swift
}

cmd_generate() {
    export XCODEGEN_DDWM_CODE_SIGN_IDENTITY="ddwm-codesign-certificate"
    local build_version="0.0.0-SNAPSHOT"
    local generate_xcodeproj=1
    local generate_cmd_help=1
    local generate_shell_parser=1
    local generate_git_hash=0

    while test $# -gt 0; do
        case $1 in
            --build-version) build_version="$2"; shift 2 ;;
            --codesign-identity) XCODEGEN_DDWM_CODE_SIGN_IDENTITY="$2"; shift 2 ;;
            --generate-git-hash) generate_git_hash=1; shift 1 ;;
            --ignore-cmd-help) generate_cmd_help=0; shift 1 ;;
            --ignore-xcodeproj) generate_xcodeproj=0; shift 1 ;;
            --ignore-shell-parser) generate_shell_parser=0; shift 1 ;;
            *) echo "Unknown option $1"; exit 1 ;;
        esac
    done

    if test $generate_shell_parser = 1; then
        cmd_generate_shell_parser
    fi

    if test $generate_cmd_help = 1; then
        ./script/generate-cmd-help.sh
    fi

    cat > Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY ./script/dev.sh generate
public let ddwmAppVersion = "$build_version"
EOF

    entries() {
        for file in docs/ddwm-*.adoc; do
            if grep -q 'exec-and-forget' <<<"$file"; then
                continue
            fi
            subcommand=$(basename "$file" | sed 's/^ddwm-//' | sed 's/\.adoc$//')
            desc="$(grep :manpurpose: "$file" | sed -E 's/:manpurpose: //')"
            echo "    [\"  $subcommand\", \"$desc\"],"
        done
    }

    cat <<EOF > ./Sources/Cli/subcommandDescriptionsGenerated.swift
// FILE IS GENERATED FROM docs/ddwm-*.adoc files
// TO REGENERATE THE FILE RUN ./script/dev.sh generate

let subcommandDescriptions = [
$(entries)
]
EOF

    cat <<EOF > ./Sources/Common/gitHashGenerated.swift
// FILE IS GENERATED BY ./script/dev.sh generate
public let gitHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse HEAD; fi)"
public let gitShortHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse --short HEAD; fi)"
EOF

    if test $generate_xcodeproj = 1; then
        export XCODEGEN_DDWM_VERSION=$build_version
        ./script/install-dep.sh --xcodegen
        ./.deps/xcodegen/xcodegen
    fi
}

cmd_build_debug() {
    local clean_cache=0
    local build_args=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --clean-cache|--clean-caches|--clean)
                clean_cache=1
                shift
                ;;
            *)
                build_args+=("$1")
                shift
                ;;
        esac
    done

    if [[ "$clean_cache" = 1 ]]; then
        rm -rf .build .debug .deps .bundle
    fi

    cmd_generate --ignore-xcodeproj --ignore-cmd-help --ignore-shell-parser
    if [[ ${#build_args[@]} -gt 0 ]]; then
        swift build "${build_args[@]}"
    else
        swift build
    fi

    if [[ "$(/usr/bin/xcode-select -p 2>/dev/null || true)" != *"CommandLineTools"* ]]; then
        if [[ ${#build_args[@]} -gt 0 ]]; then
            swift build --target AppBundleTests "${build_args[@]}"
        else
            swift build --target AppBundleTests
        fi
    else
        echo "warning: Skipping AppBundleTests build (XCTest unavailable without full Xcode)" > /dev/stderr
    fi

    local bin_path
    if [[ ${#build_args[@]} -gt 0 ]]; then
        bin_path="$(swift build --show-bin-path "${build_args[@]}")"
    else
        bin_path="$(swift build --show-bin-path)"
    fi
    rm -rf .debug && mkdir .debug
    cp "$bin_path/ddwm" .debug
    cp "$bin_path/ddwmApp" .debug
}

cmd_run_cli() {
    cmd_build_debug > /dev/null || cmd_build_debug
    ./.debug/ddwm "$@"
}

cmd_run_debug() {
    cmd_build_debug
    ./.debug/ddwmApp "$@"
}

cmd_run_swift_test() {
    if [[ "$(/usr/bin/xcode-select -p 2>/dev/null || true)" == *"CommandLineTools"* ]]; then
        echo "warning: Skipping swift test (XCTest unavailable without full Xcode)" > /dev/stderr
        return 0
    fi
    swift test
}

cmd_format() {
    local check_uncommitted_files=0
    while test $# -gt 0; do
        case $1 in
            --check-uncommitted-files) check_uncommitted_files=1; shift 1 ;;
            *) echo "Unknown option $1"; exit 1 ;;
        esac
    done

    if test $check_uncommitted_files -eq 1; then ./script/check-uncommitted-files.sh; fi

    ./script/install-dep.sh --swiftformat
    ./.deps/swiftformat/swiftformat .

    if test $check_uncommitted_files -eq 1; then ./script/check-uncommitted-files.sh; fi

    if [[ "$(/usr/bin/xcode-select -p 2>/dev/null || true)" != *"CommandLineTools"* ]]; then
        ./script/install-dep.sh --swiftlint
        ./.deps/swiftlint/swiftlint lint --quiet --fix
    else
        echo "warning: Skipping swiftlint (sourcekitd unavailable without full Xcode)" > /dev/stderr
    fi
}

cmd_run_tests() {
    ./script/check-uncommitted-files.sh
    cmd_build_debug -Xswiftc -warnings-as-errors
    cmd_run_swift_test

    ./.debug/ddwm -h > /dev/null
    ./.debug/ddwm --help > /dev/null
    ./.debug/ddwm -v | grep -q "0.0.0-SNAPSHOT SNAPSHOT"
    ./.debug/ddwm --version | grep -q "0.0.0-SNAPSHOT SNAPSHOT"

    cmd_format --check-uncommitted-files

    local generate_args=()
    local has_java_runtime=0
    if command -v java > /dev/null 2>&1; then
        if [[ -x /usr/libexec/java_home ]]; then
            /usr/libexec/java_home > /dev/null 2>&1 && has_java_runtime=1
        else
            java -version > /dev/null 2>&1 && has_java_runtime=1
        fi
    fi
    if test $has_java_runtime -eq 0; then
        echo "warning: Skipping shell parser generation (Java runtime unavailable)" > /dev/stderr
        generate_args+=(--ignore-shell-parser)
    fi
    if [[ "$(/usr/bin/xcode-select -p 2>/dev/null || true)" == *"CommandLineTools"* ]]; then
        echo "warning: Skipping xcodeproj generation (full Xcode unavailable)" > /dev/stderr
        generate_args+=(--ignore-xcodeproj)
    fi
    cmd_generate "${generate_args[@]}"
    ./script/check-uncommitted-files.sh
    echo
    echo "✅ All tests have passed successfully"
}

cmd_build_shell_completion() {
    ./script/install-dep.sh --complgen
    rm -rf .shell-completion && mkdir -p .shell-completion/zsh .shell-completion/fish .shell-completion/bash
    ./.deps/cargo-root/bin/complgen aot ./grammar/commands-bnf-grammar.txt \
        --zsh-script .shell-completion/zsh/_ddwm \
        --fish-script .shell-completion/fish/ddwm.fish \
        --bash-script .shell-completion/bash/ddwm

    if ! (not-outdated-bash --version | grep -q 'version 5'); then
        echo "bash version is too old. At least version 5 is required" > /dev/stderr
        exit 1
    fi
    zsh -c 'autoload -Uz compinit; compinit; source ./.shell-completion/zsh/_ddwm'
    fish -c 'source ./.shell-completion/fish/ddwm.fish'
    not-outdated-bash -c 'source ./.shell-completion/bash/ddwm'
}

cmd_build_docs() {
    ./script/install-dep.sh --bundler
    rm -rf .site && mkdir .site
    rm -rf .man && mkdir .man

    cp-docs() {
        cp -r ./docs/*.adoc "$1"
        cp -r ./docs/assets "$1"
        cp -r ./docs/util "$1"
        cp -r ./docs/config-examples "$1"
    }

    build-site() {
        cp-docs ./.site
        cp ./docs/index.html ./.site
        cd .site
        sed -E -i '' '/tag::synopsis/, /end::synopsis/ s/^(ddwm | {10})//' ddwm*
        bundler exec asciidoctor ./guide.adoc ./commands.adoc ./goodies.adoc
        cp goodies.html goodness.html
        rm -rf ./*.adoc
        cd - > /dev/null
        git rev-parse HEAD > .site/version.html
        if ! test -z "$(git status --porcelain)"; then
            echo "git working directory is dirty" >> .site/version.html
        fi
    }

    build-man() {
        cp-docs .man
        cd .man
        bundler exec asciidoctor -b manpage ddwm*.adoc
        rm -rf -- *.adoc
        cd - > /dev/null
    }

    build-site
    build-man
}

cmd_build_release() {
    local build_version="0.0.0-SNAPSHOT"
    local codesign_identity="ddwm-codesign-certificate"
    while test $# -gt 0; do
        case $1 in
            --build-version) build_version="$2"; shift 2 ;;
            --codesign-identity) codesign_identity="$2"; shift 2 ;;
            *) echo "Unknown option $1" > /dev/stderr; exit 1 ;;
        esac
    done

    cmd_build_docs
    cmd_build_shell_completion
    cmd_generate
    ./script/check-uncommitted-files.sh
    cmd_generate --build-version "$build_version" --codesign-identity "$codesign_identity" --generate-git-hash

    swift build -c release --arch arm64 --arch x86_64 --product ddwm -Xswiftc -warnings-as-errors

    rm -rf .release && mkdir .release
    local xcode_configuration="Release"
    xcodebuild -version
    xcodebuild-pretty .release/xcodebuild.log clean build \
        -scheme ddwm \
        -destination "generic/platform=macOS" \
        -configuration "$xcode_configuration" \
        -derivedDataPath .xcode-build

    git checkout .

    cp -r ".xcode-build/Build/Products/$xcode_configuration/ddwm.app" .release
    cp -r .build/apple/Products/Release/ddwm .release
    codesign -s "$codesign_identity" .release/ddwm

    check-universal-binary() {
        if ! file "$1" | grep --fixed-string -q "Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64"; then
            echo "$1 is not a universal binary"
            exit 1
        fi
    }
    check-contains-hash() {
        local hash
        hash=$(git rev-parse HEAD)
        if ! strings "$1" | grep --fixed-string "$hash" > /dev/null; then
            echo "$1 doesn't contain $hash"
            exit 1
        fi
    }

    check-universal-binary .release/ddwm.app/Contents/MacOS/ddwm
    check-universal-binary .release/ddwm
    check-contains-hash .release/ddwm.app/Contents/MacOS/ddwm
    check-contains-hash .release/ddwm
    codesign -v .release/ddwm.app
    codesign -v .release/ddwm

    mkdir -p ".release/ddwm-v$build_version/manpage" && cp .man/*.1 ".release/ddwm-v$build_version/manpage"
    cp -r ./legal ".release/ddwm-v$build_version/legal"
    cp -r .shell-completion ".release/ddwm-v$build_version/shell-completion"
    cd .release
    mkdir -p "ddwm-v$build_version/bin" && cp -r ddwm "ddwm-v$build_version/bin"
    cp -r ddwm.app "ddwm-v$build_version"
    zip -r "ddwm-v$build_version.zip" "ddwm-v$build_version"
    cd -
}

cmd_install_from_sources() {
    local rebuild=1
    while test $# -gt 0; do
        case $1 in
            --dont-rebuild) rebuild=0; shift ;;
            *) echo "Unknown option $1"; exit 1 ;;
        esac
    done

    if test $rebuild -eq 1; then
        cmd_build_release
    fi

    local install_root="${HOME}/.local/ddwm"
    rm -rf "$install_root"
    mkdir -p "$install_root/bin"
    cp -R ./.release/ddwm.app "$install_root/ddwm.app"
    cp ./.release/ddwm "$install_root/bin/ddwm"
    echo "Installed artifacts to: $install_root"
    echo "Add \$HOME/.local/ddwm/bin to your PATH if you want to run 'ddwm' directly."
}

main() {
    local cmd="${1:-help}"
    shift || true
    case "$cmd" in
        build-debug) cmd_build_debug "$@" ;;
        run-debug) cmd_run_debug "$@" ;;
        run-cli) cmd_run_cli "$@" ;;
        run-swift-test|swift-test) cmd_run_swift_test "$@" ;;
        run-tests|test) cmd_run_tests "$@" ;;
        format) cmd_format "$@" ;;
        generate) cmd_generate "$@" ;;
        generate-shell-parser) cmd_generate_shell_parser "$@" ;;
        build-shell-completion) cmd_build_shell_completion "$@" ;;
        build-docs) cmd_build_docs "$@" ;;
        build-release) cmd_build_release "$@" ;;
        install-from-sources) cmd_install_from_sources "$@" ;;
        help|-h|--help) usage ;;
        *) echo "Unknown command: $cmd"; echo; usage; exit 1 ;;
    esac
}

main "$@"
